permissions:
  issues: write
  contents: read

on:
  issues:
    types: [opened, labeled, reopened]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: MicrosoftEdge/action-issue-to-workitem@main
        env:
          ado_token: "${{ secrets.ADO_PAT }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
        with:
          # label: "sync"

          ado_organization: "enpolat"
          ado_project: "Test4CAIRA"

          ado_work_item_type: "Task"
          ado_area_path: "Test4CAIRA"
          ado_tags: "githubSync"

          ado_dont_check_if_exist: false
